### ISSUE TITLE
WeAreContent

### ISSUE THREAD

**Issue by jcsamperp** [Emirodgar/w-emirodgar-com#1]
Me gustaria que consideraras colocar WeAreContent.com como una plataforma para comprar contenidos digitales de texto (mas de 2800 proveedores), multimedia (audio, video, fotografia, traducciones, diseño con 700 proveedores) especializados en content marketing. 
gracias!

**Comment by Emirodgar** [comment]
¡Añadido! gracias por la sugerencia ;)
